### ISSUE TITLE
Cuffdiff is complaining about missing XS attribute

### ISSUE THREAD

**Issue by bgruening** [infphilo/hisat#12]
Hi,

using cuffdiff on a hisat mapped file produces the following error: 
```BAM record error: found spliced alignment without XS attribute```

**Comment by myRNASeq** [comment]
I got the same problem.
The running steps are the following: 
1. use hisat to map RNA Seq data and generate *.sam file
2. convert the *.sam  file to *.bam file and sorted it using samtools
3. use cufflinks to generate gtf file, however, it give me the errors: BAM record error: found spliced alignment without XS attribute

Thanks in advance

**Comment by myRNASeq** [comment]
BTW, the process still going on and generated very small gtf file (it is only about 25kb in file size)

**Comment by infphilo** [comment]
Please use HISAT2 (http://ccb.jhu.edu/software/hisat2) with the option --dta-cufflinks.  HISAT2 is a successor to HISAT and provides virtually the same performance as HISAT.
