### ISSUE TITLE
sra-acc option

### ISSUE THREAD

**Issue by pcantalupo** [infphilo/hisat#14]
Hello,

Does hisat perform splice alignments on all SRA accessions? or does it know to disable splicing when aligning a non RNA-Seq SRA library?

Thank you

**Comment by infphilo** [comment]
@kwrodarmer and @yaschenk - does NGS library provide a function that says it's DNA or RNA data?

**Comment by yaschenk** [comment]
No, this information is a part of SRA metadata.
It is served through WebAPI and can be obtained in XML form.

You are looking at running something like:

$ GET "http://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?sp=runinfo&acc=SRR2187298&retmode=xml" | grep Library
<LibraryName>IWG_PANEAD.NE-16-N-1_3pA</LibraryName>
<LibraryStrategy>WGS</LibraryStrategy>
<LibrarySelection>RANDOM</LibrarySelection>
<LibrarySource>GENOMIC</LibrarySource>
<LibraryLayout>PAIRED</LibraryLayout>

OR

$ GET "http://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?sp=runinfo&acc=SRR2305540&retmode=xml" | grep Library
<LibraryStrategy>RNA-Seq</LibraryStrategy>
<LibrarySelection>cDNA</LibrarySelection>
<LibrarySource>TRANSCRIPTOMIC</LibrarySource>
<LibraryLayout>PAIRED</LibraryLayout>

**Comment by infphilo** [comment]
Thank you @yaschenk  - I will modify hisat2-align (a perl wrapper) to incorporate this library information.
BTW, I recently released HISAT2, which enables alignment against a population of genomes and is a successor to both HISAT and TopHat2.  I'll focus on HISAT2, so please use HISAT2.

**Comment by yaschenk** [comment]
Congratulation with new tool.
BTW, the new NGS release at github allows application developers to set Application Name as in
https://github.com/ncbi/ngs/blob/master/ngs-sdk/examples/AlignTest.cpp:
```
ncbi::NGS::setAppVersionString ( "AlignTest.1.1.0" );
```
If you set this string, then when users are using HiSat/HiSat2 in "remote fetch mode" of SRA, we  would be able to measure how much your program is being used in this mode

**Comment by infphilo** [comment]
Thanks for the info!  I'll definitely use the new function in HISAT2.
