### ISSUE TITLE
problem with extract_splice_sites.py

### ISSUE THREAD

**Issue by WKassuhn** [infphilo/hisat#2]
Hello,

i had some difficulties getting your script to work with my gtf file. Here are some lines from it as an example:

chr1    hg38_knownGene  exon    1297    1358    0       +       .       gene_id uc032myo.1; transcript_id uc032myo.1
chr1    hg38_knownGene  exon    113518  113800  0       +       .       gene_id uc032myo.1; transcript_id uc032myo.1
chr1    hg38_knownGene  exon    114286  114547  0       +       .       gene_id uc032myo.1; transcript_id uc032myo.1

It folloes the gtf2.2 rules.
Now for the problem. It seemed to not include the transcipt_id and value into the value_dic in line 47. The result was, that i didn't find any transcripts, what resulted in an error while dividing the counts( line 140), since the program didn't enter the loop in line 71. I solved it by deleting the [:-1] behind "       for value in values[:-1]:" in line 47. Maybe its my gtf file that is messed up, but you might wanne look it up.

p.s. line numbers might be not correct, since i added some lines for debugging purpose.

best regards,
Wanja Kassuhn

**Comment by infphilo** [comment]
Each line should end with ";" and please make sure fields are separated by a Tab.

**Comment by A-N-Other** [comment]
As per @infphilo - fields are tab delimited and then the attributes field, if present (it is actually optional), is internally delimited. Individual attributes must end in a semicolon and are separated from each other with a space. Although the extract_splice_sites.py script would silently ignore it, the specification actually also requires textual attributes to be in "double quotes" ... gene_id "uc032myo.1"; transcript_id "uc032myo.1"
