### ISSUE TITLE
report XS:i with another designation

### ISSUE THREAD

**Issue by genomematt** [infphilo/hisat#8]
There are several use cases where knowing the score of the next best alignment is quite valuable.
Rather than not reporting XS:i in favour of XS:A, would it be possible to report with a non-conflicting tag such as ZS:i ?

**Comment by infphilo** [comment]
Thank you for your suggestion - I just made a change to enable HISAT to report secondary alignment scores using ZS:i as you suggested.

Thanks,
Daehwan
